// <auto-generated />
namespace DennikDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605160302350_Changemodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
